### Domino Strips

In [1]:
import numpy as np

There are three ways to cover a 3 × 2 grid with dominoes.

In [2]:
def cover_grids(n, domino, i):
    if 0 in domino:
        j = np.where(domino == 0)
        if len(j[0]) > 0:  # Check if there are any remaining zeros
            j = (j[0][0], j[1][0])  # Take the first zero position
            if (j[1] + 1) % n != 0 and domino[j[0], j[1] + 1] == 0: # Check if can place horizontally
                new_domino = np.copy(domino)
                new_domino[j[0], j[1]] = i
                new_domino[j[0], j[1] + 1] = i
                yield from cover_grids(n, new_domino, i + 1)
            if j[0] == 0 and domino[1, j[1]] == 0:  # Check if can place vertically
                new_domino = np.copy(domino) 
                new_domino[j[0], j[1]] = i
                new_domino[j[0] + 1, j[1]] = i
                yield from cover_grids(n, new_domino, i + 1)
    else:
        yield domino

(1) How many ways are there to cover a 4 × 2 grid?

In [3]:
t = 0
n = 4
domino = np.zeros((2, n))
for arr in cover_grids(n, domino, 1):
    t += 1
    print(f"Arrangement {t}:")
    print(arr[0])
    print(arr[1])
print(f"There are {t} ways to cover a {n} x 2 grid.")

Arrangement 1:
[1. 1. 2. 2.]
[3. 3. 4. 4.]
Arrangement 2:
[1. 1. 2. 3.]
[4. 4. 2. 3.]
Arrangement 3:
[1. 2. 2. 3.]
[1. 4. 4. 3.]
Arrangement 4:
[1. 2. 3. 3.]
[1. 2. 4. 4.]
Arrangement 5:
[1. 2. 3. 4.]
[1. 2. 3. 4.]
There are 5 ways to cover a 4 x 2 grid.


(2) What about a 6 × 2 grid?

In [4]:
t = 0
n = 6
domino = np.zeros((2, n))
for arr in cover_grids(n, domino, 1):
    t += 1
    print(f"Arrangement {t}:")
    print(arr[0])
    print(arr[1])
print(f"There are {t} ways to cover a {n} x 2 grid.")

Arrangement 1:
[1. 1. 2. 2. 3. 3.]
[4. 4. 5. 5. 6. 6.]
Arrangement 2:
[1. 1. 2. 2. 3. 4.]
[5. 5. 6. 6. 3. 4.]
Arrangement 3:
[1. 1. 2. 3. 3. 4.]
[5. 5. 2. 6. 6. 4.]
Arrangement 4:
[1. 1. 2. 3. 4. 4.]
[5. 5. 2. 3. 6. 6.]
Arrangement 5:
[1. 1. 2. 3. 4. 5.]
[6. 6. 2. 3. 4. 5.]
Arrangement 6:
[1. 2. 2. 3. 3. 4.]
[1. 5. 5. 6. 6. 4.]
Arrangement 7:
[1. 2. 2. 3. 4. 4.]
[1. 5. 5. 3. 6. 6.]
Arrangement 8:
[1. 2. 2. 3. 4. 5.]
[1. 6. 6. 3. 4. 5.]
Arrangement 9:
[1. 2. 3. 3. 4. 4.]
[1. 2. 5. 5. 6. 6.]
Arrangement 10:
[1. 2. 3. 3. 4. 5.]
[1. 2. 6. 6. 4. 5.]
Arrangement 11:
[1. 2. 3. 4. 4. 5.]
[1. 2. 3. 6. 6. 5.]
Arrangement 12:
[1. 2. 3. 4. 5. 5.]
[1. 2. 3. 4. 6. 6.]
Arrangement 13:
[1. 2. 3. 4. 5. 6.]
[1. 2. 3. 4. 5. 6.]
There are 13 ways to cover a 6 x 2 grid.


(3) Can you find a pattern that would help you work out the number of different ways dominoes can be used to cover any n × 2 rectangle?

In [5]:
for n in range(1,11):
    t = 0
    domino = np.zeros((2, n))
    for arr in cover_grids(n, domino, 1):
        t += 1
    print(f"There are {t} ways to cover a {n} x 2 grid.")

There are 1 ways to cover a 1 x 2 grid.
There are 2 ways to cover a 2 x 2 grid.
There are 3 ways to cover a 3 x 2 grid.
There are 5 ways to cover a 4 x 2 grid.
There are 8 ways to cover a 5 x 2 grid.
There are 13 ways to cover a 6 x 2 grid.
There are 21 ways to cover a 7 x 2 grid.
There are 34 ways to cover a 8 x 2 grid.
There are 55 ways to cover a 9 x 2 grid.
There are 89 ways to cover a 10 x 2 grid.
